#!/usr/bin/env python
# -*- c-basic-offset: 4; indent-tabs-mode: nil -*-

## Copyright 2018-2020, Lancaster University
## All rights reserved.
## 
## Redistribution and use in source and binary forms, with or without
## modification, are permitted provided that the following conditions are
## met:
## 
##  * Redistributions of source code must retain the above copyright
##    notice, this list of conditions and the following disclaimer.
## 
##  * Redistributions in binary form must reproduce the above copyright
##    notice, this list of conditions and the following disclaimer in the
##    documentation and/or other materials provided with the
##    distribution.
## 
##  * Neither the name of the copyright holder nor the names of
##    its contributors may be used to endorse or promote products derived
##    from this software without specific prior written permission.
## 
## THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
## "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
## LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
## A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
## OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
## SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
## LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
## DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
## THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
## (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
## OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
##
##
## Author: Steven Simpson <https://github.com/simpsonst>

import sys
import os
import yaml

## Locate our installation.
vpnmgrhome = os.path.realpath(sys.argv[0])
vpnmgrhome = os.path.dirname(vpnmgrhome)
vpnmgrhome = os.path.dirname(vpnmgrhome)
vpnmgrhome = os.path.dirname(vpnmgrhome)

## Script-defined arguments
authtab = sys.argv[1]

## OpenVPN-defined arguments
depth = int(sys.argv[2])
## This seems to be $tls_id_0, but we don't use it.
subjdn = sys.argv[3]

## DN attributes are now in os.environ['X509_<depth>_<attr>']
## variables.

## We only care if we're validating the client's certificate.
if depth != 0:
    exit()

## Load the configuration file.  No file means no constraints.
doc = yaml.load(open(sys.argv[1], 'r'))
if doc is None:
    exit(0)

def process_array(doc, stopon, defval):
    for elem in doc:
        if process_expr(elem) == stopon:
            return not defval
    return defval

def process_and(doc):
    return process_array(doc, False, True)

def process_or(doc):
    return process_array(doc, True, False)

def process_expr(doc):
    global depth
    if type(doc) is dict:
        if 'and' in doc:
            return process_and(doc['and'])
        if 'or' in doc:
            return process_or(doc['or'])
        if 'key' in doc and 'value' in doc:
            key = 'X509_%d_%s' % (depth, doc['key'])
            expected = doc['value']
            return key in os.environ and os.environ[key] == expected
        ## TODO: Support regex?
    return True

## Check that the DN is compatible with the settings in
## $authtab.  See verify-cn (maybe in /usr/share/openvpn/) for an
## example script.
            
exit(0 if process_expr(doc) else 1)

## When invoked, this is what the environment looks like:
# config=config.ovpn
# daemon=0
# daemon_log_redirect=0
# daemon_pid=9188
# daemon_start_time=1583228697
# proto_1=udp
# remote_1=XX.XX.XX.XX
# remote_port_1=15046
# script_type=tls-verify
# tls_digest_0=a1:fd:b8:ad:3a:f8:76:28:d3:c8:c0:e5:1a:7a:8f:54:f2:64:08:f4
# tls_digest_1=12:1f:ac:ec:c2:ec:87:a8:05:ad:f3:1a:f8:67:39:7e:27:ce:4f:47
# tls_digest_sha256_0=8f:45:ea:c6:0b:56:e2:e5:ee:8b:e7:ee:47:61:66:61:9f:84:b8:8a:5e:24:e3:0c:c2:d8:c1:7d:24:d8:dc:e3
# tls_digest_sha256_1=87:0f:f3:f0:51:90:78:60:43:19:27:f6:84:a7:5c:63:ff:48:2e:fb:6a:5b:5c:c2:45:44:32:ea:dd:59:d7:98
# tls_id_0=C=GB, ST=Doncashire, L=Donopolis, O=Donopolis University, OU=Doss-around Department, CN=client-username, emailAddress=doss@doncs.example.org
# tls_id_1=C=GB, ST=Doncashire, L=Donopolis, O=Donopolis University, OU=Doss-around Department, CN=cust-ca, emailAddress=doss@doncs.example.org
# tls_serial_0=174226832081305022276693777672095421444
# tls_serial_1=466846157150813033287425987904493138577747548958
# tls_serial_hex_0=83:12:de:07:82:db:61:c6:45:b3:23:35:c4:e8:54:04
# tls_serial_hex_1=51:c6:1b:0f:15:ae:02:ef:76:23:cc:7d:5f:ac:db:d1:84:af:1b:1e
# untrusted_ip=XX.XX.XX.XX
# untrusted_port=15046
# verb=1
# X509_0_C=GB
# X509_0_CN=client-username
# X509_0_emailAddress=doss@doncs.example.org
# X509_0_L=Donopolis
# X509_0_O=Donopolis University
# X509_0_OU=Doss-around Department
# X509_0_ST=Doncashire
# X509_1_C=GB
# X509_1_CN=cust-ca
# X509_1_emailAddress=doss@doncs.example.org
# X509_1_L=Donopolis
# X509_1_O=Donopolis University
# X509_1_OU=Doss-around Department
# X509_1_ST=Doncashire
